steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.web
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WEB_IMAGE}:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WEB_IMAGE}:latest
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WEB_IMAGE}:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WEB_IMAGE}:latest

substitutions:
  _REGION: us-central1
  _REPOSITORY: kanban-repo
  _WEB_IMAGE: 46kg-web
  _NEXT_PUBLIC_API_BASE_URL: https://replace-after-api-deploy.example.com
